swagger: '2.0'
basePath: /
paths:
  /:
    get:
      responses:
        '200':
          description: Success
        '500':
          description: Upload service not operational
      summary: Endpoint for Index/Root Route
      operationId: get_root
      tags:
      - default
  /api/v0/publish:
    get:
      responses:
        '200':
          description: Success
    post:
      responses:
        '200':
          description: Success
        '400':
          description: Input payload validation failed
      summary: Endpoint for upload and publish requests
      operationId: post_publish
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            $ref: '#/definitions/PublishJSON'
      tags:
        - default
  /api/v0/version:
    get:
      responses:
        '200':
          description: Success
      summary: Endpoint for getting the current version
      operationId: get_version
      tags:
        - default
  /metrics:
    get:
      responses:
        '200':
          description: Success
      summary: Endpoint for Metrics
      operationId: get_metrics
      tags:
      - default
info:
  title: AIOPS Publisher API
  version: 0.0.1
  description: AIOPS Publisher API
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: default
    description: Default namespace
definitions:
  PublishJSON:
    required:
      - id
      - data
    properties:
      id:
        type: string
        example: '123'
      data:
        example: []
      ai_service:
        type: string
        example: generic_ai
    type: object
